name: docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login to docker hub
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run:|
          docker buildx build --push \
            --tag "${{secrets.DOCKER_REGISTRY}}"/apiemitter:${{github.run_id}}${{github.run_attempt}} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            ./src/ApiEmitter/  
